### ISSUE TITLE
"TFS"?

### ISSUE THREAD

**Issue by azazar** [ticki/tfs#15]
Why "TFS"? It's quite confusing. There are several file systems with the same abbreviation. Maybe it should be renamed while it's not too late?

**Comment by StefanoD** [comment]
That's true.

https://github.com/alibaba/tfs

**Comment by polymetric1** [comment]
I think it's Ticki Filesystem. Honestly it sounds like a temp name. Maybe it could be named after a chemical or element or something like the other Redox things.

**Comment by ticki** [comment]
I like TFS, and will use that at least for now. I'll reevaluate before initial release.
