### ISSUE TITLE
Building tfs under other platforms

### ISSUE THREAD

**Issue by kallisti5** [ticki/tfs#4]
Any chance of being able to build tfs under platforms other than Redox OS?

```
$ cargo build
   Compiling tfs v0.1.0 (file:///home/kallisti5/Code/tfs)
error: file not found for module `config`
 --> src/lib.rs:1:5
  |
1 | mod config;
  |     ^^^^^^
  |
  = help: name the file either config.rs or config/mod.rs inside the directory "src"

error: aborting due to previous error

error: Could not compile `tfs`.

To learn more, run the command again with --verbose.
```

**Comment by kallisti5** [comment]
It would be interesting to try and create wrappers about the rust tfs driver on other platforms :-)

**Comment by ticki** [comment]
Currently the build is broken - on every platform. I'll notify you when it's ready.

**Comment by gitbugged** [comment]
Please notify me as well, really looking forward to giving this a test run!
