### ISSUE TITLE
Seahash weaknesses

### ISSUE THREAD

**Issue by Veedrac** [ticki/tfs#5]
Your comments say

    /// It is generally suspected that this is at least partially secure (i.e. you cannot deduce the
    /// seed, even with unlimited "black box" access to the function), but it has not yet been subject
    /// to proper cryptoanalysis.

This seems fairly naïve, since it's relatively simple to deduce `k ^ diffuseⁿ(k)` (`n ≥ 1`) for any of the keys `k`. Though I don't personally know how you would invert this function, `diffuse(a)` is trivially reversible and this is a lot of information to give an attacker. Is there any particular reason you believe this to be hard to invert?

---

To deduce `a ^ diffuse(a)`, just take

    let abcd = undiffuse(hash(&[0; 0])) ^ 0;
    let Abcd = undiffuse(hash(&[0; 8])) ^ 8;
    let aA = abcd ^ Abcd;

where `undiffuse` is the inverse of `diffuse`. `a ^ diffuse²(a)` just requires replacing `Abcd` in the above with `undiffuse(hash(to_bytes(Aa))) ^ 8`, and so on for higher powers. The other keys just require different array lengths.

**Comment by ticki** [comment]
Issue is just that you don't know the keys. The comment is specifically aimed towards the case where keys aren't known.

**Comment by Veedrac** [comment]
If you can reverse `k ^ diffuse(k)` you can discover `k`, a key. This seems fairly likely, since that function is far from cryptographically secure.

**Comment by ticki** [comment]
How would you revert `k ^ diffuse(k)`? If you have a general solution, you have broken Davies–Meyer, which I doubt is the case.

Note that `k ^ diffuse(k)` is not bijective, so it isn't possible to revert with a single candidate. However, if you can show some form of statistical bias, you can weaken bruteforcing.

That being said, people realy shouldn't rely on it as a secure PRF before proper analysis has taken place.

**Comment by ticki** [comment]
I'm going to remove the clause on security. Way too many people have mistaken it for cryptographic hash function (like SHA-3).

**Comment by ticki** [comment]
Here's an actual attack on SeaHash:

You can extract  ![](http://latex.codecogs.com/svg.latex?h%20%3D%20k_1%20%5Coplus%20k_2%20%5Coplus%20k_3%20%5Coplus%20k_4) relatively easily: Hash the string `""` and revert the final diffusion: ![](http://latex.codecogs.com/svg.latex?h%20%3D%20f%5E%7B-1%7D%28H%28%22%22%29%29)

Now, if I know ![](http://latex.codecogs.com/svg.latex?%28k_1%2C%20k_2%2C%20k_3%29), I can extract ![](http://latex.codecogs.com/svg.latex?k_4%20%3D%20k_1%20%5Coplus%20k_2%20%5Coplus%20k_3%20%5Coplus%20h).

The consequence is that the minimal search space is ![](http://latex.codecogs.com/svg.latex?2%5E%7B3%20%5Ccdot%2064%7D%20%3C%202%5E%7B4%20%5Ccdot%2064%7D), i.e. smaller than the state space.

**Comment by Veedrac** [comment]
The attack I give reduces the search space to four separate searches of size 2^64, so is significantly better than your attack.

This involves breaking `k ^ diffuse(k)`, which likely isn't very hard. It would be hard if `diffuse` was a strong PRF, but it's not - it's really weak.

**Comment by ticki** [comment]
Maybe I'm just misunderstanding, but your attack doesn't seem to take the finalization into account? You can't reverse the XOR sum of the states.

**Comment by Veedrac** [comment]
`hash(&[0; 0])` produces `diffuse(a ^ b ^ c ^ d)`.

`hash(&[0; 8])` produces `diffuse(diffuse(a) ^ b ^ c ^ d ^ 8)`.

If then you

    let abcd = undiffuse(hash(&[0; 0])) ^ 0;
    let Abcd = undiffuse(hash(&[0; 8])) ^ 8;

you have that `abcd` is `a ^ b ^ c ^ d` and `Abcd` is `diffuse(a) ^ b ^ c ^ d`.

Thus `abcd ^ Abcd` is `a ^ diffuse(a)`. You can brute-force this in time 2^64 (though I suspect a cryptographer can do better). You can make similar constructions for `b ^ diffuse(b)`, `c ^ diffuse(c)` and `d ^ diffuse(d)`.

Does that clarify things?

**Comment by Veedrac** [comment]
Woo! I solved it!

I used this program in the Z3 SMT solver

    (declare-const key (_ BitVec 64))

    (define-fun mul ((x (_ BitVec 64))) (_ BitVec 64)
      (bvmul x #x6eed0e9da4d94a4f))

    (assert (= #b1011
               ((_ extract 63 60) (mul key))))

    (assert (= #x9da697d493f4897d
               (bvxor key
                      (mul (bvxor (mul key)
                                  (bvlshr (mul key) (_ bv43 64)))))))

    (check-sat)
    (get-model)

Note that this hard-codes `a >> 60`, so in reality you'd need to run this 16x for each possibility. After just under half an hour the solver deduced the answer

    sat
    (model 
      (define-fun key () (_ BitVec 64)
        #x16f11fe89b0d677c)
    )
    z3 z3file  1725.70s user 0.25s system 99% cpu 28:46.31 total

**Comment by ticki** [comment]
Cool (annoying, but still). I see now how you go from one to another. Color me impressed.

> After just under half an hour the solver deduced the answer

That was fast.

**Comment by ticki** [comment]
I'm going to close this as it wasn't a goal to have this kind of keyed security but rather a presumed feature. I've removed everything questioning the security and replaced it with disclaimers saying very clearly that it is not secure.
